/// <reference lib="dom" />

/**
 * perf-large-diagram.spec.ts
 *
 * Edit-mode interaction latency tests for a large deterministic diagram
 * (~120 elements, ~158 relationships).  These tests prove that the visual
 * layout client stays responsive at realistic diagram sizes — a gap that the
 * existing bench gate (render-only, small fixture) does not cover.
 *
 * Performance budgets (CI-tolerant, documented here and asserted below):
 *
 *   ┌──────────────────────────────────────────────────────┬──────────────┐
 *   │ Operation                                            │ Budget       │
 *   ├──────────────────────────────────────────────────────┼──────────────┤
 *   │ Edit-mode enable (click toggle → aria-pressed=true)  │ < 1500 ms    │
 *   │ Single arrow-key move round-trip (keydown → DOM upd) │ <  200 ms    │
 *   │ Stage + save operation (save click → accepted msg)   │ < 3000 ms    │
 *   └──────────────────────────────────────────────────────┴──────────────┘
 *
 * CI margin: budgets already include 2× the observed local baseline to absorb
 * headless-Chromium startup, iCloud-Drive I/O variability, and CI runner noise.
 * If a budget is exceeded consistently, investigate the client-script hot path
 * rather than widening the margin here.
 *
 * Fixture: test/visual-layout/large-diagram-harness.html (generated by
 * generate-large-diagram-harness.js; 120 nodes, 158 edges, deterministic grid
 * layout — no randomness).
 *
 * Related issue: #89 (R7/T2-9)
 */

import { expect, Page, test } from '@playwright/test';
import { execFileSync } from 'child_process';
import * as path from 'path';
import * as url from 'url';

const ROOT = path.resolve(__dirname, '../..');

const HARNESS =
  process.env.C4X_LARGE_DIAGRAM_HARNESS ??
  path.join(ROOT, 'test/visual-layout/large-diagram-harness.html');

const GENERATOR = path.join(ROOT, 'test/visual-layout/generate-large-diagram-harness.js');

/**
 * Performance budgets (milliseconds).
 *
 * These are intentionally conservative to remain green across headless CI
 * environments. Tighten only after the baseline is stable for 5+ consecutive
 * CI runs; document the change here with the observed local P95.
 */
const BUDGET = {
  /**
   * Time from clicking the edit-toggle to the toggle reporting aria-pressed=true
   * (i.e. the client has processed the mode switch and updated the DOM).
   * The client must iterate all 120 nodes to set tabindex; budget covers that.
   */
  editModeEnable: 1500,

  /**
   * Time from pressing ArrowRight on a selected node to the DOM reflecting the
   * new x coordinate (data-current-x updated).  Client must update a single
   * node's transform and announce the move; edges need no re-layout.
   */
  arrowKeyMoveRoundTrip: 200,

  /**
   * Time from clicking Save to the batchAccepted message appearing in
   * __visualLayoutMessages.  Includes serialising all staged edits and
   * the stub postMessage round-trip (synchronous in the harness).
   */
  stageSave: 3000,
} as const;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

test.beforeAll(() => {
  execFileSync(process.execPath, [GENERATOR, HARNESS], { cwd: ROOT });
});

async function loadHarness(page: Page): Promise<void> {
  await page.goto(url.pathToFileURL(HARNESS).href);
  // Wait until the client script has rendered at least one node into the DOM.
  await page.waitForFunction(
    () => document.querySelector('g.node') !== null,
    undefined,
    { timeout: 10_000 },
  );
}

async function enterEditMode(page: Page): Promise<void> {
  await page.locator('#toggle-layout').click();
  await expect(page.locator('#toggle-layout')).toHaveAttribute('aria-pressed', 'true', {
    timeout: BUDGET.editModeEnable + 500,
  });
}

/** Return the data-current-x value for a node (set by the client after a move). */
async function nodeCurrentX(page: Page, id: string): Promise<number> {
  const value = await page.locator(`g.node[data-id="${id}"]`).getAttribute('data-current-x');
  return Number(value);
}

interface PostedMessage {
  type?: string;
  protocolVersion?: number;
  revision?: string;
  edits?: Array<{ id: string; x?: number; y?: number }>;
}

function getMessages(page: Page): Promise<PostedMessage[]> {
  return page.evaluate(() => {
    const w = window as Window & { __visualLayoutMessages?: PostedMessage[] };
    return w.__visualLayoutMessages ?? [];
  });
}

// ---------------------------------------------------------------------------
// Performance tests
// ---------------------------------------------------------------------------

test('perf: edit-mode enable completes within budget on 120-node diagram', async ({ page }) => {
  await loadHarness(page);

  const toggle = page.locator('#toggle-layout');
  await expect(toggle).toBeEnabled();

  const t0 = Date.now();
  await toggle.click();

  // Wait until aria-pressed=true — this is the completion signal.
  await expect(toggle).toHaveAttribute('aria-pressed', 'true', {
    timeout: BUDGET.editModeEnable + 500,
  });
  const elapsed = Date.now() - t0;

  // Assert the budget.
  expect(
    elapsed,
    `Edit-mode enable took ${elapsed} ms; budget is ${BUDGET.editModeEnable} ms`,
  ).toBeLessThan(BUDGET.editModeEnable);

  // Sanity: at least one node should now have tabindex=0 (edit mode active).
  await expect(page.locator('g.node').first()).toHaveAttribute('tabindex', '0');
});

test('perf: single arrow-key move round-trip is within budget on 120-node diagram', async ({ page }) => {
  await loadHarness(page);
  await enterEditMode(page);

  // Pick the first node for the move.
  const firstNode = page.locator('g.node').first();
  const nodeId = await firstNode.getAttribute('data-id');
  expect(nodeId).toBeTruthy();

  // Select and focus the node.
  await firstNode.focus();
  await page.keyboard.press('Enter');
  await expect(firstNode).toHaveAttribute('aria-selected', 'true');

  const xBefore = await nodeCurrentX(page, nodeId!);

  // Measure only the keypress → DOM-update round-trip.
  const t0 = Date.now();
  await page.keyboard.press('ArrowRight');

  // Poll until data-current-x changes, up to budget + 500 ms grace.
  await page.waitForFunction(
    ([id, prev]: [string, number]) => {
      const el = document.querySelector(`g.node[data-id="${id}"]`);
      return el !== null && Number(el.getAttribute('data-current-x')) !== prev;
    },
    [nodeId, xBefore] as [string, number],
    { timeout: BUDGET.arrowKeyMoveRoundTrip + 500 },
  );
  const elapsed = Date.now() - t0;

  expect(
    elapsed,
    `Arrow-key move round-trip took ${elapsed} ms; budget is ${BUDGET.arrowKeyMoveRoundTrip} ms`,
  ).toBeLessThan(BUDGET.arrowKeyMoveRoundTrip);

  // Verify the x coordinate actually moved (correctness guard).
  const xAfter = await nodeCurrentX(page, nodeId!);
  expect(xAfter).toBeGreaterThan(xBefore);
});

test('perf: stage + save operation completes within budget on 120-node diagram', async ({ page }) => {
  await loadHarness(page);
  await enterEditMode(page);

  // Stage a move on the first node.
  const firstNode = page.locator('g.node').first();
  const nodeId = await firstNode.getAttribute('data-id');
  expect(nodeId).toBeTruthy();

  await firstNode.focus();
  await page.keyboard.press('Enter');
  await page.keyboard.press('ArrowRight');

  // Confirm the change is staged (dirty state).
  await expect(page.locator('#layout-status')).toHaveAttribute('data-state', 'dirty', {
    timeout: 2_000,
  });

  // Measure the save operation.
  const messagesBefore = (await getMessages(page)).length;

  const t0 = Date.now();
  await page.locator('#save-staged-changes').click();

  // Wait until the batchAccepted message appears.
  await page.waitForFunction(
    (prevCount: number) => {
      const w = window as Window & { __visualLayoutMessages?: unknown[] };
      const msgs = w.__visualLayoutMessages ?? [];
      return msgs.length > prevCount;
    },
    messagesBefore,
    { timeout: BUDGET.stageSave + 500 },
  );
  const elapsed = Date.now() - t0;

  expect(
    elapsed,
    `Stage+save took ${elapsed} ms; budget is ${BUDGET.stageSave} ms`,
  ).toBeLessThan(BUDGET.stageSave);

  // Correctness guard: the save message must reference the first node.
  const allMessages = await getMessages(page);
  const saveMsg = allMessages
    .reverse()
    .find((m): m is PostedMessage => m.type === 'visualLayout.applySemanticEdits');
  expect(saveMsg).toBeDefined();
  expect(Array.isArray(saveMsg?.edits)).toBe(true);
  expect(saveMsg?.edits?.some((e) => e.id === nodeId)).toBe(true);
});
